spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wefshine321/SpringcloudConfig
          search-paths: respo
          username: 1016499401@qq.com
          password: wxwuxia1101
      label: master
  application:
    name: config-server
server:
  port: 8769
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/